export const GET_ALL_TOPICS = 'GET_ALL_TOPICS';
export const GET_ALL_TOPICS_DETAILS = 'GET_ALL_TOPICS_DETAILS';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';

export const SET_FILTERED_TOPICS = 'SET_FILTERED_TOPICS';
export const SET_ON_CLICK_TOPIC = 'SET_ON_CLICK_TOPIC';
export const SET_ON_CLICK_TOPIC_DETAILS = 'SET_ON_CLICK_TOPIC_DETAILS';

export const SET_PROFILE = 'SET_PROFILE';
export const REMOVE_PROFILE = 'REMOVE_PROFILE';
