export const GET_ALL_TOPICS = 'GET_ALL_TOPICS';
export const GET_ALL_TOPICS_DETAILS = 'GET_ALL_TOPICS_DETAILS';

export const ERROR_MESSAGE = 'ERROR_MESSAGE';

export const SET_FILTERED_TOPICS = 'SET_FILTERED_TOPICS'
